version: '3.7'

services:
  config-service:
    image: mgo02/config-service:latest
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://config-server:8888" ]
      interval: 5s
      timeout: 5s
      retries: 10000


  eureka:
    image: mgo02/eureka-service:latest
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
    environment:
      eureka.instance.hostname: eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka


  gateway:
    image: mgo02/gateway-service:1.2
    ports:
      - 8080:8080
    depends_on:
      - config-service
      - eureka
    networks:
      - spring-cloud-network
    environment:
      server.port: 80880
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka


  user-wallet:
    image: mgo02/user-wallet:latest
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - eureka
    networks:
      - spring-cloud-network


  user-profile:
    image: mgo02/user-profile:latest
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - eureka
    networks:
      - spring-cloud-network


networks:
  spring-cloud-network:
    name: spring-cloud-network
    driver: bridge
